### ISSUE TITLE
Rubrik tab - recent backups not showing

### ISSUE THREAD

**Issue by rh1f10** [southampton/cortex#307]
Hi,

In going through systems recently for DRC project, I've noticed that quite a few systems that are in Rubrik, have an SLA policy assign and have been backing up successfully - but are NOT showing in the Rubrik tab in cortex.

Some examples of this occurring are when you search the following systems:

srv02299 (Should be AgressoMS7-Prod SLA)
srv00642 (Should be Blacboard-Prod SLA)

Plenty of systems are showing correctly, I haven't been through all of them but a small sample highlighted the issue to me.

Can has fix?

Cheers,

Ryan

**Comment by claytonpeters** [comment]
Done a bit of digging on this. We match against VMs in Rubrik by name, and when we ask for srv02299, we're actually getting back two VMs (it's doing a search rather than a literal match), only one of which is the correct one, but we're only taking the first hit, so we're showing information for the wrong VM.

We do store moId in the cache table, which might be a better thing to use here. I'll sort that for the next release.

**Comment by jakemalley** [comment]
I was just typing a reply to this but you've beat me to it....
I've seen this problem before when doing some of the Rubrik API stuff, if we are storing the ID let's use that. Also I guess we shouldn't be provisioning VMs with names such as DR-srv12345 and instead either making a new VM number of new class.

**Comment by jakemalley** [comment]
Using the ID will likely speed up the page load time as we can use the endpoint: `/vmware/vm/{id}`

**Comment by claytonpeters** [comment]
So, this has required a bit more thinking, but it's been sorted on a separate branch now. We don't have the Rubrik object managed ID in the database, we only have VMware UUID and VMware moId. We can't directly use VMware moId because they're not unique across vCenters, and the Rubrik API lacks the ability to say "give me a VM with this moID on this vCenter".

As such, I've made a function which works out the Rubrik object managed ID by pulling the list of vCenters from Rubrik (which is relatively quick), then calculating the VM object managed ID from that (VirtualMachine:::<rubrik-vcenter-object-id>-<vm-moid>) and then calling /vmware/vm/{id} for that object.

This solves the issue of VMs with identical names, and VMs with identical moIDs. I also spotted that rubrik.py was in both lib/ and corpus/ so I've put a stop to that now by making the one in lib/ a thin wrapper around the one in corpus/ by just getting it to source it's config differently.
