### ISSUE TITLE
Changing specs on standard VM makes for confusing changes in pricing

### ISSUE THREAD

**Issue by claytonpeters** [southampton/cortex#342]
The prices it shows are correct, but the specs don't necessarily change to what you might suspect.

**Comment by jakemalley** [comment]
There was a bug in the way the slides were getting updated, they were "correct" in terms of their actual value but the range of the slider was updated each time, so when selecting a specification the range of the slider would become say 32-256 GB Ram instead of 0-256, therefore it appeared the slider was at "0". Fixed in v6.
