### ISSUE TITLE
Rubrik tab: Do not protect SLA assignment broke

### ISSUE THREAD

**Issue by rh1f10** [southampton/cortex#344]
Hi,

When we assign an SLA Domain to a system in Cortex via the Rubrik tab, we have the option of "DO NOT PROTECT".

This effectively marks a VM to no longer backup in  Rubik. If the system has already had backups when the poke to not protect is made via cortex it bins off the VM into the "Snapshot Retention" area (formerly, unmanaged snapshots). 

When this happens, the VM remains unprotected with the existing backups for the system marked with a retention SLA of "forever". 

When you "do not protect" via the GUI, you have the additional options of 'existing snapshot retention'. Here it is possible to:

Use the current SLA for retention (preferred, it will age out accordingly)
Keep forever (insta-delete all the backup data)
Expire immediatley

I think we need cortex to behave in a way where if you mark it as "do not protect" it sets the option of "keep the current SLA for retention". 

Happy to discuss this further if needed.

Ryan

**Comment by rh1f10** [comment]
A further note on this, if we delete a VM (It become a relic in Rubrik speak, no longer in vCenter) in the normal fashion in the decommission workflow, the system automatically marks them correctly as relic and they keep their previously assigned SLA Domain and expire out gracefully as expected.

**Comment by jakemalley** [comment]
@rh1f10 I'll take a look at this - when selecting "DO NOT PROTECT" we currently update the `vmware/vm/{id}` object in Rubrik via the PATCH API and set `configuredSlaDomainId = UNPROTECTED`.

I would imagine there is an additional field that needs to be configured in order to set the retention policy to "existing" or similar. 

During the decom workflow we don't do anything with Rubrik, I would imagine Rubrik detects the VM is no longer in vCenter and then applies some policies based on it seeing the VM has been deleted.

**Comment by rh1f10** [comment]
Hi,

Yes you are right Jake. Because we just delete the VM, Rubrik see’s it is no longer in vCenter and marks it as a relic. The default behaviour (only recent as it saved us extra dev work) is to mark it as a relic with the original policy it was assigned to age out.

We just need the behaviour the same if someone marks it as “do not protect”.

Noice

Ryan

**Comment by jakemalley** [comment]
Fixed in v6
