### ISSUE TITLE
Write the standard server workflow

### ISSUE THREAD

**Issue by divad** [southampton/cortex#5]

**Comment by claytonpeters** [comment]
- Workflow to have sliders to show the actual configuration, rather than the "additional" selection. Make it so that when you choose a base-type, that sets the minimum on the sliders.

- In the form, add a ticket number field.

- In the form, add a description / purpose. This should go in the notes field in VMware, possibly in some sort of YAML format.

**Comment by claytonpeters** [comment]
Workflow now has sliders, form has incident task / project task field (NOT ticket number, deliberately), which is linked to the CI in ServiceNow. Form also now has purpose, which populates ServiceNow short_description field, which is utilised by the Puppet ENC and is also added to the Notes field in VMware. Form also has a comments field which populates the longer comments box in ServiceNow.

**Comment by divad** [comment]
I'm resolving this as theres no point having a tracking task for it.
